package com.peak.action;

import com.peak.db.DBUtils;
import com.peak.util.PathUtil;

import java.io.File;
import java.io.IOException;

public class AutoGenerateDBScriptAction {

    public static void main(String[] args) throws IOException {
        DBUtils.generatePatchFile();
        java.awt.Desktop.getDesktop().open(new File(PathUtil.generatePatchPath("script/")));
    }
}
